receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost"
            - "http://localhost:5173"
          allowed_headers:
            - "*"

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  otlphttp/traces:
    endpoint: http://grafana:4318
    tls:
      insecure: true

  otlphttp/metrics:
    endpoint: http://grafana:4318
    tls:
      insecure: true

  otlphttp/logs:
    endpoint: http://grafana:4318
    tls:
      insecure: true

  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/traces, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/metrics, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs, debug]

  extensions: [health_check]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
